server:
    port: 8081

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
#                    issuer-uri: http://localhost:8080/realms/oauth2
                    jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
#                    audiences: http://localhost:8081 # 수신자 위치
#                    public-key-location: classpath:certs/publicKey.txt # OAuth 2.0 JWS 검증용 PublicKey 파일 위치
